= geo查询
:lang: zh

geo查询是指按照地理位置进行过滤.

.elastic支持四种geo查找过滤器.
. `geo_bounding_box` 找出落在指定矩形框中的点
  * 盒模型, 通过判断经纬度是否在指定范围内即可. 盒模型是基础模型
. `geo_distance` 找出与指定位置在指定距离内的点
  * 距离模型, 通常做法是先画圆的外接正方形, 然后判断正方形内的点与指定点的距离
. `geo_distance_range` 找出与指定位置在指定距离范围内的点
  * 同距离, 只不过需要外圆的外接正方形, 内圆的内接正方形, 然后计算距离.
. `geo_polygon` 找出落在多边形内的点

geo 过滤性能消耗较高, 所以通常会先使用其他过滤条件减少查询范围.

`geo_distance` 过滤器本身只负责过滤, 不输出具体距离.
可以通过排序(sort) 可以获取具体的距离. 具体参考文档 
link:https://www.elastic.co/guide/cn/elasticsearch/guide/current/sorting-by-distance.html[sorting 
by distance]

[[geohash]]
== 了解geohash
geohash 是一种将地理位置(lon/lat)编码为字符串的方式, 初衷是为了使坐标在url上更好的展示.
现在geohash已经变成一种在数据库中有效索引坐标点和地理形状的方式.

geohash 将世界分为32个格子(4行8列), 每个格子都用一个字母/数字表示. 每个格子又可以继续
细分为32个格子, 不断重复下去. 

所以, geohash 长度越长, 精度越高, 共同前缀长度越长, 离得越近.
但是, 离得越近, 共同前缀长度不一定越长(如相邻但分到了两个高等阶单元格).

== 聚合
聚合是指对查找到的地理位置进行分组, 如按距离分组或者其他条件.

最常见的, 如我们查询附近商家时, 会分为 1km以内, `1~2km`, `2~5km` 等组, 这就是聚合.

elastic 有三种聚合手段处理地理位置.
1. 距离聚合: 将文档围绕一个中心点分组, 多用于查找附近点.
2. geohash 网格聚合: 按照geohash范围分组, 多用于显示在地图上.
3. 地理边界: 返回所有坐标点的边界, 多用于确定地图缩放比例, 避免地图上展示大量空白.

具体自行参考文档
